services:
  db:
    image: postgres:16-alpine
    container_name: minilms-db
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - minilms-db-data:/var/lib/postgresql/data
    networks:
      - minilms-network

  api:
    build: .
    container_name: minilms-api
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - minilms-network

volumes:
  minilms-db-data:

networks:
  minilms-network:
    driver: bridge